# Install dependencies only when needed
FROM node:lts-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# If using npm with a `package-lock.json` comment out above and use below instead
# COPY package.json package-lock.json ./
# RUN npm ci

# Rebuild the source code only when needed
FROM node:lts-alpine AS builder

ENV NODE_ENV production

COPY --from=deps node_modules node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn export

# If using npm comment out above and use below instead
# RUN npm run build

# Production image, copy all the files and run next
FROM nginx:stable-alpine AS runner
WORKDIR /usr/local/nginx

COPY --from=builder .next/server/pages /usr/share/nginx/html
COPY --from=builder .next/static /usr/share/nginx/html/_next/static

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
