# This is a basic workflow to help you get started with Actions

name: Uploader

on:
  release:
    types: [ created ]

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 14.x
          cache: yarn
      
      - name: Build react scripts
        run: yarn install && yarn build
        env:
          CI: false

      - name: Upload COS
        uses: jaehue/tencent-cos-action@v0.1.0
        with:
          args: delete -r -f / && upload -rs build/ /
          secret_id: ${{ secrets.TENCENT_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_SECRET_KEY }}
          bucket: ungine-official-1307412436
          region: ap-shanghai
