# This is a basic workflow to help you get started with Actions

name: Uploader

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upload COS
        uses: jaehue/tencent-cos-action@v0.1.0
        with:
          args: delete -r -f / && upload -rs assets/ assets/ && upload index.html / && upload 404.html /
          secret_id: ${{ secrets.TENCENT_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_SECRET_KEY }}
          bucket: ungine-official-1307412436
          region: ap-shanghai
